export type ProgramAvailabilityTone = "current" | "limited" | "ending" | "unresolved";

export type ProgramResearch = {
  name: string;
  officialUrl?: string;
  sourceUrl?: string;
  sourceLabel: string;
  availability: string;
  availabilityTone: ProgramAvailabilityTone;
  scope: string;
};

// Official-source research observed on 18 July 2026. Detailed evidence and publication
// gaps live in docs/card-benefits-source-audit.md. Keep unresolved claims unresolved.
export const programResearch: Record<string, ProgramResearch> = {
  "nexo-card": {
    name: "Nexo Card",
    officialUrl: "https://nexo.com/eea/crypto-card",
    sourceUrl: "https://nexo.com/eea/crypto-card",
    sourceLabel: "Nexo card and loyalty table",
    availability: "Available in supported EEA and UK markets",
    availabilityTone: "current",
    scope: "One card with Credit and Debit modes. Base, Silver, Gold, and Platinum are loyalty levels, not separate cards.",
  },
  "coinbase-card": {
    name: "Coinbase Card",
    officialUrl: "https://help.coinbase.com/en/coinbase/trading-and-funding/coinbase-card/cb-card",
    sourceUrl: "https://help.coinbase.com/en/coinbase/trading-and-funding/coinbase-card/cb-card-rewards",
    sourceLabel: "Coinbase debit card help",
    availability: "US debit-card offering",
    availabilityTone: "current",
    scope: "This profile covers the Coinbase Visa debit card. Coinbase One Card is a separate American Express credit product.",
  },
  "binance-card": {
    name: "Binance Card",
    officialUrl: "https://www.binance.com/pt-BR",
    sourceUrl: "https://www.binance.com/pt-BR",
    sourceLabel: "Binance Brazil",
    availability: "Current offering found for Brazil",
    availabilityTone: "limited",
    scope: "Older EEA card terms are historical. Current Brazil fees and rewards still need a dedicated official terms capture.",
  },
  kripicard: {
    name: "Kripicard",
    officialUrl: "https://home.kripicard.com/",
    sourceUrl: "https://home.kripicard.com/fees",
    sourceLabel: "Kripicard fees",
    availability: "Premium virtual card available",
    availabilityTone: "current",
    scope: "Premium is the current virtual-card product, not a separate issuer or loyalty tier. Cashback remains on the roadmap.",
  },
  "cdc-visa": {
    name: "Crypto.com Card",
    officialUrl: "https://crypto.com/cards",
    sourceUrl: "https://help.crypto.com/en/articles/12017612-level-up-rewards-and-benefits",
    sourceLabel: "Crypto.com Level Up benefits",
    availability: "Available in supported markets",
    availabilityTone: "limited",
    scope: "Prepaid-card terms vary by region. The US Visa Signature credit card is a separate offering and must be compared separately.",
  },
  "bybit-card": {
    name: "Bybit Card",
    officialUrl: "https://www.bybit.com/en/help-center/article/FAQ-Bybit-Card-General-Inquiries",
    sourceUrl: "https://www.bybit.com/en/help-center/article/Introduction-to-Bybit-Card-Rewards",
    sourceLabel: "Bybit Card Rewards",
    availability: "Availability and card type vary by issuing region",
    availabilityTone: "limited",
    scope: "Base through Infinite are reward levels driven by spend or VIP mapping, not separate card plans.",
  },
  "kast-card": {
    name: "KAST Card",
    officialUrl: "https://www.kast.xyz/crypto-cards",
    sourceUrl: "https://www.kast.xyz/crypto-cards",
    sourceLabel: "KAST crypto cards",
    availability: "Available plans advertised",
    availabilityTone: "limited",
    scope: "Standard, Premium, Limited, and Luxe are card plans. Seasonal points and MOVE rewards are separate programs and must not be added together.",
  },
  "gemini-card": {
    name: "Gemini Credit Card",
    officialUrl: "https://www.gemini.com/credit-card",
    sourceUrl: "https://support.gemini.com/hc/en-us/articles/4405148512923-Product-Overview",
    sourceLabel: "Gemini product overview",
    availability: "US credit-card offering",
    availabilityTone: "current",
    scope: "One WebBank Mastercard credit card. Merchant-specific Vault offers sit outside the base reward table.",
  },
  "metamask-card": {
    name: "MetaMask Card",
    officialUrl: "https://support.metamask.io/trade/metamask-card/what-is-metamask-card/",
    sourceUrl: "https://support.metamask.io/trade/metamask-card/card-faq/",
    sourceLabel: "MetaMask Card FAQ",
    availability: "New US and UK sign-ups paused",
    availabilityTone: "limited",
    scope: "Virtual and Metal are plans in one program. New Metal orders have also been paused since 2 June 2026.",
  },
  "etherfi-card": {
    name: "ether.fi Cash",
    officialUrl: "https://www.ether.fi/cash",
    sourceUrl: "https://help.ether.fi/en/articles/303625-how-do-membership-levels-work",
    sourceLabel: "ether.fi membership levels",
    availability: "Available in supported markets",
    availabilityTone: "current",
    scope: "Core, Luxe, Pinnacle, and VIP are membership levels earned through points or ETHFI holdings, not separate catalog cards.",
  },
  "wirex-card": {
    name: "Wirex Card",
    officialUrl: "https://www.wirexapp.com/en-sg/stablecoin-and-crypto-card",
    sourceUrl: "https://www.wirexapp.com/post/discover-wirex-one-s-new-membership-model",
    sourceLabel: "Wirex One membership model",
    availability: "Available in supported markets",
    availabilityTone: "current",
    scope: "Wirex One Base, Premium, Elite, Private, and Bespoke replace older Cryptoback membership tables.",
  },
  "bitpay-card": {
    name: "BitPay Card",
    officialUrl: "https://bitpay.com/wallet-verify/get-started",
    sourceUrl: "https://bitpay.com/wallet-verify/get-started",
    sourceLabel: "BitPay application status",
    availability: "New applications temporarily paused",
    availabilityTone: "limited",
    scope: "Previous rewards and card agreements are historical. Current replacement-program economics have not been published.",
  },
  "coca-card": {
    name: "COCA Card",
    officialUrl: "https://coca.xyz/card",
    sourceUrl: "https://help.coca.xyz/support/solutions/articles/205000042710-tier-system-terms-conditions",
    sourceLabel: "COCA tier terms",
    availability: "Available in supported markets",
    availabilityTone: "limited",
    scope: "Starter through Elite are staking-based loyalty tiers. The exact official tier table is image-based and awaits structured review.",
  },
  "brighty-card": {
    name: "Brighty Card",
    officialUrl: "https://brighty.app/",
    sourceUrl: "https://brighty.app/en/subscription-terms-and-conditions",
    sourceLabel: "Brighty subscription terms",
    availability: "Available in supported markets",
    availabilityTone: "limited",
    scope: "Brighty One, Plus, and Pro are subscription plans. Current prices and plan-specific rates are disclosed in the app.",
  },
  "cypher-card": {
    name: "Cypher Card",
    officialUrl: "https://cypherhq.io/plans",
    sourceUrl: "https://cypherhq.io/plans",
    sourceLabel: "Cypher plans and wind-down notice",
    availability: "Services end 6 September 2026",
    availabilityTone: "ending",
    scope: "Premium is no longer sold. Legacy benefits apply only to existing users during the wind-down.",
  },
  "venmo-card": {
    name: "Venmo Credit Card",
    officialUrl: "https://help.venmo.com/cs/articles/venmo-credit-card-faq-vhel312",
    sourceUrl: "https://help.venmo.com/cs/articles/venmo-credit-card-rewards-program-terms-and-cash-back-to-crypto-terms-vhel127",
    sourceLabel: "Venmo rewards and crypto terms",
    availability: "US credit-card offering",
    availabilityTone: "current",
    scope: "This is a fiat credit card with optional Cash Back to Crypto, not a crypto-funded debit card.",
  },
  "bitrefill-card": {
    name: "Bitrefill Card",
    officialUrl: "https://www.bitrefill.com/card",
    sourceUrl: "https://www.bitrefill.com/card/rewards",
    sourceLabel: "Bitrefill Card rewards",
    availability: "Available in supported European markets",
    availabilityTone: "current",
    scope: "Starter and Plus are verification levels that change limits, not paid reward plans.",
  },
  "whitebit-card": {
    name: "WhiteBIT Nova",
    officialUrl: "https://whitebit.com/crypto-card",
    sourceUrl: "https://help.whitebit.com/hc/en-gb/articles/23273438576925-WhiteBIT-N%C3%B3va-debit-card",
    sourceLabel: "WhiteBIT Nova help",
    availability: "Available in supported EEA markets",
    availabilityTone: "current",
    scope: "One card with user-selected cashback categories; no separate card tiers were found.",
  },
  "wayex-card": {
    name: "Wayex Card",
    officialUrl: "https://www.wayex.com/en/faq/",
    sourceUrl: "https://help.wayex.com/en/articles/9167149-frequently-asked-questions",
    sourceLabel: "Wayex Australia FAQ",
    availability: "Regional offerings available",
    availabilityTone: "limited",
    scope: "The Australian crypto-to-AUD card and global USD stablecoin card have different issuers and economics.",
  },
  "gnosis-card": {
    name: "Gnosis Pay",
    officialUrl: "https://gnosispay.com/",
    sourceUrl: "https://help.gnosispay.com/hc/en-us/articles/40288567337876-Intermediary-Cashback-Programme",
    sourceLabel: "Gnosis Pay cashback terms",
    availability: "Available in supported European markets",
    availabilityTone: "current",
    scope: "GNO holdings create promotional reward levels, not separate cards. Current cashback terms end 30 September 2026.",
  },
  "fold-card": {
    name: "Fold Card",
    officialUrl: "https://foldapp.com/pricing",
    sourceUrl: "https://foldapp.com/pricing",
    sourceLabel: "Fold pricing",
    availability: "Debit card available; credit card limited-launch",
    availabilityTone: "limited",
    scope: "This profile covers Fold debit. Member and Fold+ are debit memberships; Fold credit is a separate product.",
  },
  "bleap-card": {
    name: "Bleap Card",
    officialUrl: "https://www.bleap.finance/en-us/card",
    sourceUrl: "https://www.bleap.finance/legal-agreements/cashback-terms-and-conditions",
    sourceLabel: "Bleap cashback terms",
    availability: "Available in supported markets",
    availabilityTone: "current",
    scope: "One card with merchant-category rewards; the restaurant and supermarket campaign ended 31 May 2026.",
  },
  "bitpanda-card": {
    name: "Bitpanda Card",
    officialUrl: "https://support.bitpanda.com/hc/en-us/articles/360018933120-What-is-the-Bitpanda-Card-and-what-are-its-benefits",
    sourceUrl: "https://support.bitpanda.com/hc/articles/4413398057490-Bitpanda-Card-cashback-applicability",
    sourceLabel: "Bitpanda cashback eligibility",
    availability: "Available in supported European markets",
    availabilityTone: "current",
    scope: "One card. Former BEST VIP reward tiers ended in April 2025 and are not current benefits.",
  },
  "zypto-card": {
    name: "Zypto Card",
    officialUrl: "https://zypto.com/personal/crypto-cards/",
    sourceUrl: "https://help.zypto.com/en/articles/14665487-zypto-card-types-explained",
    sourceLabel: "Zypto card types",
    availability: "Multiple card products available",
    availabilityTone: "limited",
    scope: "Premium reloadable Visa and nonreloadable virtual cards are different offerings. Ecosystem loyalty is separate.",
  },
  "ledger-card": {
    name: "Ledger CL Card",
    officialUrl: "https://shop.ledger.com/pages/cl-card-crypto-card",
    sourceUrl: "https://shop.ledger.com/pages/cl-card-crypto-card",
    sourceLabel: "Current Ledger CL Card page",
    availability: "Available in supported markets",
    availabilityTone: "current",
    scope: "One card with region-dependent providers. The current page supersedes the legacy 2% BXX reward page.",
  },
  "tuyo-card": {
    name: "Tuyo Card",
    officialUrl: "https://tuyo.com/card",
    sourceUrl: "https://tuyo.com/rewards",
    sourceLabel: "Tuyo rewards",
    availability: "Virtual card available",
    availabilityTone: "current",
    scope: "Physical cards and ATM support are coming soon. Points mechanics remain app- and terms-dependent.",
  },
  "redotpay-card": {
    name: "RedotPay Card",
    officialUrl: "https://www.redotpay.com/card/",
    sourceUrl: "https://helpcenter.redotpay.com/en/articles/14686020-getting-started-with-redotpay-pro",
    sourceLabel: "RedotPay Pro guide",
    availability: "Available in supported markets",
    availabilityTone: "current",
    scope: "Standard is the base card. Pro monthly and annual are optional subscriptions with different included cards and allowances.",
  },
  "tria-card": {
    name: "Tria Card",
    officialUrl: "https://www.tria.so/card",
    sourceUrl: "https://help.tria.so/en/articles/13696877-cashback-general-information",
    sourceLabel: "Tria cashback guide",
    availability: "Available in supported markets",
    availabilityTone: "current",
    scope: "Virtual, Signature, and Premium are plans. Staking badges and dated campaigns modify rewards separately.",
  },
  "avici-card": {
    name: "Avici Card",
    officialUrl: "https://avici.money/",
    sourceUrl: "https://docs.avici.money/getting-started/secured-credit-cards",
    sourceLabel: "Avici secured-card docs",
    availability: "Launch status conflicts across official pages",
    availabilityTone: "unresolved",
    scope: "The homepage says coming soon while current docs describe creating and using cards. Benefits are not treated as live entitlements.",
  },
  "oobit-card": {
    name: "Oobit Card",
    officialUrl: "https://www.oobit.com/crypto-card",
    sourceUrl: "https://www.oobit.com/legal/5x-reward-terms",
    sourceLabel: "Oobit 5X reward terms",
    availability: "Available in supported markets",
    availabilityTone: "limited",
    scope: "Rewards depend on the asset and campaign. Reward stablecoins are restricted to in-app Tap to Pay use.",
  },
  "plutus-card": {
    name: "Plutus Card",
    officialUrl: "https://www.plutus.it/plans",
    sourceUrl: "https://www.plutus.it/blog/plutus-q1-migration-faq",
    sourceLabel: "Plutus migration FAQ",
    availability: "Card return timing is stale and unresolved",
    availabilityTone: "unresolved",
    scope: "Paid plans and PLU Reward Levels are two independent choices. The published Q2 2026 relaunch date has passed.",
  },
  "deblock-card": {
    name: "Deblock Card",
    officialUrl: "https://deblock.com/",
    sourceUrl: "https://cdn1.deblock.com/terms/fee_info/Fees_Pages_Deblock_EN_v6.3.pdf",
    sourceLabel: "Deblock fee schedule effective 5 July 2026",
    availability: "Available in supported markets",
    availabilityTone: "current",
    scope: "Standard and Premium are subscriptions; Native is unlocked by holding a Deblock NFT for at least 30 days.",
  },
  "ready-lite": {
    name: "Ready Card",
    officialUrl: "https://www.ready.co/card",
    sourceUrl: "https://www.ready.co/blog/card-faqs",
    sourceLabel: "Ready Card FAQs",
    availability: "Available in supported markets",
    availabilityTone: "current",
    scope: "Lite and Metal are plans inside one Ready Card program, not separate catalog cards.",
  },
  "tapx-card": {
    name: "TapX Card",
    sourceLabel: "Catalog issuer domain",
    availability: "Official source identity unresolved",
    availabilityTone: "unresolved",
    scope: "The catalog domain does not resolve. A similarly named .io site is not used until ownership and legal continuity are established.",
  },
  "fiat24-card": {
    name: "Fiat24 Card",
    officialUrl: "https://docs.fiat24.com/user/payments/mastercard-debit",
    sourceUrl: "https://docs.fiat24.com/products/pricing-for-individuals",
    sourceLabel: "Fiat24 individual pricing",
    availability: "Available in supported markets",
    availabilityTone: "current",
    scope: "Standard, Premium, and Ultimate are account-NFT tiers that also set card limits and top-up fees.",
  },
  "thorwallet-card": {
    name: "THORWallet Card",
    officialUrl: "https://www.thorwallet.org/",
    sourceUrl: "https://faqs.thorwallet.org/features/thorwallet-mastercard",
    sourceLabel: "THORWallet Mastercard guide",
    availability: "Current and legacy plan pages conflict",
    availabilityTone: "unresolved",
    scope: "The homepage lists Basic and Premium, while older docs list Standard, Gold, and Platinum. No selector is shown until reconciled.",
  },
  "safepal-card": {
    name: "SafePal Card",
    officialUrl: "https://www.safepal.com/en/bank",
    sourceUrl: "https://www.safepal.com/en/blog/safepal-launches-1st-crypto-friendly-banking-gateway-and-visa-card",
    sourceLabel: "SafePal banking gateway and tiers",
    availability: "Available in supported markets",
    availabilityTone: "limited",
    scope: "A SafePal-branded Fiat24 account and card. Account points set loyalty tier; the public tier table still needs structured review.",
  },
  "ur-card": {
    name: "UR Card",
    officialUrl: "https://docs.ur.app/hc/en-us/articles/12916060053775-UR-Mastercard-Debit-Card",
    sourceUrl: "https://docs.ur.app/hc/en-us/articles/12916060053775-UR-Mastercard-Debit-Card",
    sourceLabel: "UR Mastercard guide",
    availability: "Virtual card available",
    availabilityTone: "current",
    scope: "One free virtual card. No physical card, PIN, ATM access, or official cashback program was found.",
  },
  "savepay-card": {
    name: "SavePay Card",
    officialUrl: "https://savepay.gitbook.io/savepay/getting-started/activate-your-savepay-card",
    sourceUrl: "https://savepay.gitbook.io/savepay/getting-started/activate-your-savepay-card",
    sourceLabel: "SavePay card activation",
    availability: "Fiat24-based integration",
    availabilityTone: "limited",
    scope: "SavePay distributes a Fiat24 account and card. SavePay-specific fees and countries still need direct terms evidence.",
  },
  "imtoken-card": {
    name: "imToken Card",
    officialUrl: "https://www.token.im/card?locale=en",
    sourceUrl: "https://token.im/card/DCS/fee",
    sourceLabel: "imToken DCS fees",
    availability: "Multiple regional products",
    availabilityTone: "limited",
    scope: "imToken distributes separate Fiat24 debit and DCS Singapore credit products. Their fees and benefits cannot be merged.",
  },
  "tokenpocket-card": {
    name: "TokenPocket Card",
    officialUrl: "https://card.tokenpocket.pro/?locale=en",
    sourceUrl: "https://card.tokenpocket.pro/?locale=en",
    sourceLabel: "TokenPocket card portal",
    availability: "Fiat24-based virtual card",
    availabilityTone: "limited",
    scope: "Partner-specific fees and exact regional eligibility are not yet disclosed in structured public terms.",
  },
  "bitgetwallet-card": {
    name: "Bitget Wallet Card",
    officialUrl: "https://web3.bitget.com/card",
    sourceUrl: "https://web3.bitget.com/en/academy/how-to-apply-for-the-bitget-wallet-card-step-by-step-guide-for-new-users",
    sourceLabel: "Bitget Wallet regional application guide",
    availability: "Regional offerings available",
    availabilityTone: "limited",
    scope: "DCS, Fiat24, and Immersve serve different regions. Physical-card support is limited to named APAC markets.",
  },
};

export function getProgramResearch(slug: string) {
  return programResearch[slug];
}
