import type { OfficialSourceDefinition } from "./priority-official-sources";

export const catalogExpansionSources: OfficialSourceDefinition[] = [
  {
    candidateKey: "okx-card",
    slug: "okx-card-eea-cashback-2026",
    title: "OKX Card EEA ongoing cashback FAQ",
    url: "https://www.okx.com/en-eu/help/okx-card-eea-ongoing-cashback-faq",
    authorityTier: "B",
    sourceType: "official issuer regional reward guide",
    facts: [
      { fieldKey: "eea_reward_tier_standard", displayValue: "EEA Standard: 2% USDG; €10 monthly cap", valueJson: { name: "Standard", rewardPercent: 2, monthlyCap: 10, capCurrency: "EUR", maximumEligibleSpend: 500, tierOrder: 1 }, scopeJson: { region: "EEA", dimension: "account_tier", effectiveFrom: "2026-03-01" }, requiredTerms: ["Non-VIP", "2%", "10 EUR"] },
      { fieldKey: "eea_reward_tier_vip1", displayValue: "EEA VIP 1: 4% USDG; €300 monthly cap", valueJson: { name: "VIP 1", rewardPercent: 4, monthlyCap: 300, capCurrency: "EUR", maximumEligibleSpend: 7500, tierOrder: 2 }, scopeJson: { region: "EEA", dimension: "account_tier" }, requiredTerms: ["VIP", "4%", "300 EUR"] },
      { fieldKey: "eea_reward_tier_vip2", displayValue: "EEA VIP 2: 4.5% USDG; €450 monthly cap", valueJson: { name: "VIP 2", rewardPercent: 4.5, monthlyCap: 450, capCurrency: "EUR", maximumEligibleSpend: 10000, tierOrder: 3 }, scopeJson: { region: "EEA", dimension: "account_tier" }, requiredTerms: ["4.5%", "450 EUR", "10,000 EUR"] },
      { fieldKey: "eea_reward_tier_vip3", displayValue: "EEA VIP 3: 5% USDG; €1,000 monthly cap", valueJson: { name: "VIP 3", rewardPercent: 5, monthlyCap: 1000, capCurrency: "EUR", maximumEligibleSpend: 20000, tierOrder: 4 }, scopeJson: { region: "EEA", dimension: "account_tier" }, requiredTerms: ["5%", "1,000 EUR", "20,000 EUR"] },
      { fieldKey: "eea_reward_tier_vip4_plus", displayValue: "EEA VIP 4+: 10% USDG; €1,000 monthly cap", valueJson: { name: "VIP 4+", rewardPercent: 10, monthlyCap: 1000, capCurrency: "EUR", maximumEligibleSpend: 10000, tierOrder: 5 }, scopeJson: { region: "EEA", dimension: "account_tier" }, requiredTerms: ["4+", "10%", "10,000 EUR"] },
      { fieldKey: "eea_reward_qualification", displayValue: "Cashback applies only to USDG-funded purchases and pays to OKX Pay in USDG", scopeJson: { region: "EEA", fundingAsset: "USDG", rewardAsset: "USDG" }, requiredTerms: ["USDG purchases", "Pay account"] },
    ],
  },
  {
    candidateKey: "kucard",
    slug: "kucard-new-zealand-cashback-2026",
    title: "How KuCard Cashback Works",
    url: "https://www.kucoin.com/support/33128183226777",
    authorityTier: "B",
    sourceType: "official issuer regional reward guide",
    facts: [
      { fieldKey: "eligibility_scope", displayValue: "New Zealand residents only", scopeJson: { countries: ["NZ"], residencyRequired: true }, requiredTerms: ["exclusively", "residents of New Zealand"] },
      { fieldKey: "reward_tier_vip0", displayValue: "VIP 0: 1%; 1.2% holding KCS; 1.7% above 100 KCS", valueJson: { name: "VIP 0", basePercent: 1, kcsHolderPercent: 1.2, kcsAbove100Percent: 1.7, tierOrder: 1 }, scopeJson: { dimension: "account_tier", region: "NZ" }, requiredTerms: ["VIP 0", "1.2%", "1.7%"] },
      { fieldKey: "reward_tier_vip1_4", displayValue: "VIP 1–4: 1.5%; 100 USDC monthly cap", valueJson: { name: "VIP 1-4", rewardPercent: 1.5, monthlyCap: 100, capCurrency: "USDC", tierOrder: 2 }, scopeJson: { dimension: "account_tier", region: "NZ" }, requiredTerms: ["VIP 1-4", "1.5%", "100"] },
      { fieldKey: "reward_tier_vip5_7", displayValue: "VIP 5–7: 2%; 200 USDC monthly cap", valueJson: { name: "VIP 5-7", rewardPercent: 2, monthlyCap: 200, capCurrency: "USDC", tierOrder: 3 }, scopeJson: { dimension: "account_tier", region: "NZ" }, requiredTerms: ["VIP 5-7", "2%", "200"] },
      { fieldKey: "reward_tier_vip8_10", displayValue: "VIP 8–10: 2.5%; 240 USDC monthly cap", valueJson: { name: "VIP 8-10", rewardPercent: 2.5, monthlyCap: 240, capCurrency: "USDC", tierOrder: 4 }, scopeJson: { dimension: "account_tier", region: "NZ" }, requiredTerms: ["VIP 8-10", "2.5%", "240"] },
      { fieldKey: "reward_tier_vip11_12", displayValue: "VIP 11–12: 3%; 250 USDC monthly cap", valueJson: { name: "VIP 11-12", rewardPercent: 3, monthlyCap: 250, capCurrency: "USDC", tierOrder: 5 }, scopeJson: { dimension: "account_tier", region: "NZ" }, requiredTerms: ["VIP 11-12", "3%", "250"] },
      { fieldKey: "loyalty_bonus", displayValue: "KCS Loyalty can add up to 5.5%, for up to 8.5% total", valueJson: { additionalMaximumPercent: 5.5, combinedMaximumPercent: 8.5 }, scopeJson: { separateDimension: "loyalty_level", region: "NZ" }, requiredTerms: ["additional up to 5.5%", "up to 8.5%"] },
    ],
  },
  {
    candidateKey: "gate-card",
    slug: "gate-card-rewards-2026",
    title: "Gate Card rewards system and benefits",
    url: "https://miniapp.gate.com/blog/gate-card-how-to-earn-up-to-8-percent-cashback-points-system-and-member-benefits-explained",
    authorityTier: "B",
    sourceType: "official issuer reward guide",
    facts: [
      { fieldKey: "reward_tier_t0", displayValue: "T0: VIP 0–4 or $0 monthly spend; 1%; $5 cap", valueJson: { name: "T0", vipRange: [0, 4], spendThreshold: 0, rewardPercent: 1, monthlyCap: 5, tierOrder: 1 }, scopeJson: { dimension: "reward_tier" }, requiredTerms: ["T0", "VIP 0 - VIP 4", "1.00%"] },
      { fieldKey: "reward_tier_t1", displayValue: "T1: VIP 5–7 or $500 monthly spend; 1%; $50 cap", valueJson: { name: "T1", vipRange: [5, 7], spendThreshold: 500, rewardPercent: 1, monthlyCap: 50, tierOrder: 2 }, scopeJson: { dimension: "reward_tier" }, requiredTerms: ["T1", "VIP 5 - VIP 7", "500"] },
      { fieldKey: "reward_tier_t2", displayValue: "T2: VIP 8 or $3,000 monthly spend; 2%; $100 cap", valueJson: { name: "T2", vipLevels: [8], spendThreshold: 3000, rewardPercent: 2, monthlyCap: 100, tierOrder: 3 }, scopeJson: { dimension: "reward_tier" }, requiredTerms: ["T2", "3,000", "2.00%"] },
      { fieldKey: "reward_tier_t3", displayValue: "T3: VIP 9 or $6,000 monthly spend; 3%; $150 cap", valueJson: { name: "T3", vipLevels: [9], spendThreshold: 6000, rewardPercent: 3, monthlyCap: 150, tierOrder: 4 }, scopeJson: { dimension: "reward_tier" }, requiredTerms: ["T3", "6,000", "3.00%"] },
      { fieldKey: "reward_tier_t4", displayValue: "T4: VIP 10–12 or $10,000 monthly spend; 5%; $250 cap", valueJson: { name: "T4", vipRange: [10, 12], spendThreshold: 10000, rewardPercent: 5, monthlyCap: 250, tierOrder: 5 }, scopeJson: { dimension: "reward_tier" }, requiredTerms: ["T4", "VIP 10 - VIP 12", "5.00%"] },
      { fieldKey: "reward_tier_t5", displayValue: "T5: VIP 13–14 or $15,000 monthly spend; 8%; $400 cap", valueJson: { name: "T5", vipRange: [13, 14], spendThreshold: 15000, rewardPercent: 8, monthlyCap: 400, tierOrder: 6 }, scopeJson: { dimension: "reward_tier" }, requiredTerms: ["T5", "VIP 13 - VIP 14", "8.00%"] },
      { fieldKey: "reward_redemption", displayValue: "100 points = 1 USDT; points redeem for USDT or GT and do not expire", valueJson: { points: 100, redemptionAmount: 1, redemptionAsset: "USDT", otherAsset: "GT", expires: false }, scopeJson: { eligibleTransactionsOnly: true }, requiredTerms: ["100 points = 1 USDT", "Points never expire"] },
      { fieldKey: "card_type", displayValue: "Visa card linked to Gate Pay", scopeJson: { product: "Gate Card" }, requiredTerms: ["Visa card", "Gate Pay account"] },
    ],
  },
  {
    candidateKey: "uphold-card",
    slug: "uphold-card-rewards-2026",
    title: "Uphold Card rewards",
    url: "https://support.uphold.com/hc/en-us/articles/41106030548763-Earning-rewards",
    authorityTier: "B",
    sourceType: "official issuer regional plan and reward guide",
    facts: [
      { fieldKey: "uk_reward", displayValue: "UK: 1% GBP cashback on GBP-funded purchases; £100 monthly cap", valueJson: { rewardPercent: 1, rewardCurrency: "GBP", monthlyCap: 100, capCurrency: "GBP" }, scopeJson: { country: "GB", fundingAsset: "GBP", cryptoFundedRewards: false }, requiredTerms: ["Uphold Debit Card in the UK", "1% cashback in GBP", "£100"] },
      { fieldKey: "us_plan_essential", displayValue: "US Essential: $0 annual; 2% XRP; $120 monthly cap", valueJson: { name: "Essential", annualFee: 0, rewardPercent: 2, rewardCurrency: "XRP", monthlyCap: 120, tierOrder: 1 }, scopeJson: { country: "US", dimension: "card_plan" }, requiredTerms: ["Essential tier", "$0", "2% back"] },
      { fieldKey: "us_plan_elite", displayValue: "US Elite: $99.99/year; 4% XRP on crypto/metals or 3% on fiat/stablecoins; $300 cap", valueJson: { name: "Elite", annualFee: 99.99, cryptoAndMetalsPercent: 4, fiatAndStablecoinsPercent: 3, rewardCurrency: "XRP", monthlyCap: 300, tierOrder: 2 }, scopeJson: { country: "US", dimension: "card_plan", autoRenewal: true }, requiredTerms: ["Elite tier", "$99.99", "4%", "$300"] },
    ],
  },
  {
    candidateKey: "bit2me-card",
    slug: "bit2me-space-center-terms",
    title: "Bit2Me Space Center terms",
    url: "https://legal.bit2me.com/en/support/solutions/articles/35000293220-t-c-space-center",
    authorityTier: "A",
    sourceType: "official loyalty program legal terms",
    facts: [
      { fieldKey: "loyalty_dimension", displayValue: "Space Center levels 0–7 replace the old tier system", valueJson: { minimumLevel: 0, maximumLevel: 7 }, scopeJson: { dimension: "loyalty_level", oldTierSystem: "obsolete" }, requiredTerms: ["level 0", "level 7", "replace the old Tier System"] },
      { fieldKey: "reward_qualification", displayValue: "Card cashback depends on Space Center level; exact current level benefits are in the authenticated profile", scopeJson: { publicRateTable: "not disclosed", authenticatedProfileRequired: true }, requiredTerms: ["cashback percentage", "User's level in Space Center"] },
    ],
  },
  {
    candidateKey: "tangem-pay",
    slug: "tangem-pay-plans",
    title: "Tangem Pay plans",
    url: "https://tangem.com/en/tangem-pay/",
    authorityTier: "B",
    sourceType: "official issuer current and announced plan guide",
    facts: [
      { fieldKey: "card_plan_basic", displayValue: "Basic: $0; 3 cards; $10,000 daily limit; Visa Platinum", valueJson: { name: "Basic", fee: 0, cards: 3, dailySpendLimit: 10000, networkTier: "Visa Platinum", tierOrder: 1 }, scopeJson: { dimension: "card_plan", lifecycle: "LIVE", rewardsAnnouncedNotLive: true }, requiredTerms: ["Basic", "Start from $0", "$10,000 daily spending limit"] },
      { fieldKey: "card_plan_plus", displayValue: "Plus: $29/month; 5 cards; $50,000 daily limit; announced", valueJson: { name: "Plus", monthlyFee: 29, cards: 5, dailySpendLimit: 50000, networkTier: "Visa Signature", tierOrder: 2 }, scopeJson: { dimension: "card_plan", lifecycle: "WAITLIST", termsMayChange: true }, requiredTerms: ["Plus", "$29/month", "Coming soon"] },
      { fieldKey: "card_plan_premium", displayValue: "Prestige: $999/year; 10 cards; $100,000 daily limit; Visa Infinite; announced", valueJson: { name: "Prestige", annualFee: 999, cards: 10, dailySpendLimit: 100000, networkTier: "Visa Infinite", tierOrder: 3 }, scopeJson: { dimension: "card_plan", lifecycle: "WAITLIST", termsMayChange: true, formerObservedName: "Premium" }, requiredTerms: ["Prestige", "$999/year", "$100,000", "Visa Infinite"] },
      { fieldKey: "future_reward_matrix", displayValue: "Announced rewards: Basic/Plus/Prestige show 5%/10%/15% on the first $500, then 1%/2%/4%, with $100/$500/$1,000 monthly caps", valueJson: { Basic: { first500Percent: 5, ongoingPercent: 1, monthlyCapUsd: 100 }, Plus: { first500Percent: 10, ongoingPercent: 2, monthlyCapUsd: 500 }, Prestige: { first500Percent: 15, ongoingPercent: 4, monthlyCapUsd: 1000 } }, scopeJson: { lifecycle: "ANNOUNCED", publishAsCurrent: false, termsMayChange: true }, requiredTerms: ["Cashback, first $500", "15%", "Monthly cashback cap", "$1000"] },
      { fieldKey: "future_benefit_matrix", displayValue: "Announced ATM fees are 4%/2%/1%; Plus and Prestige add warranty and price protection; lounge access is paid/2 visits/8 visits", valueJson: { Basic: { atmPercent: 4, lounge: "paid", warranty: false, priceProtection: false }, Plus: { atmPercent: 2, loungeVisits: 2, warranty: true, priceProtection: true }, Prestige: { atmPercent: 1, loungeVisits: 8, warranty: true, priceProtection: true } }, scopeJson: { lifecycle: "ANNOUNCED", publishAsCurrent: false, termsMayChange: true }, requiredTerms: ["ATM Fees", "4%", "2 free visits a year", "8 free visits a year", "Extended warranty", "Price protection"] },
      { fieldKey: "funding_model", displayValue: "Tangem Wallet remains self-custodial; KYC applies to Tangem Pay account", scopeJson: { walletCustody: "self-custodial", kyc: true }, requiredTerms: ["Self-custodial by design", "KYC and eligibility checks"] },
    ],
  },
  {
    candidateKey: "coinjar-card",
    slug: "coinjar-card-fees-limits",
    title: "CoinJar Card fees and limits",
    url: "https://support.coinjar.com/hc/en-au/articles/4403702613529-CoinJar-Card-fees-and-limits",
    authorityTier: "B",
    sourceType: "official issuer fee and limit guide",
    facts: [
      { fieldKey: "issuance_fee", displayValue: "Verified explicit zero digital and physical issuance fee", valueJson: { amount: 0, currency: "AUD" }, scopeJson: { country: "AU" }, requiredTerms: ["Card issuance", "$0"] },
      { fieldKey: "annual_fee", displayValue: "Verified explicit zero monthly and annual fees", valueJson: { amount: 0, currency: "AUD" }, scopeJson: { country: "AU" }, requiredTerms: ["monthly or annual fees"] },
      { fieldKey: "purchase_fee_reward", displayValue: "1% purchase fee returned as CoinJar Reward Points", valueJson: { feePercent: 1, returnedAs: "CoinJar Reward Points" }, scopeJson: { country: "AU", eligibleTransactionsOnly: true }, requiredTerms: ["1% of the transaction amount", "returned to you as CoinJar Reward Points"] },
      { fieldKey: "fx_fee", displayValue: "Mastercard rate plus 2.99%", valueJson: { rate: 2.99, unit: "percent" }, scopeJson: { nonAudTransactions: true }, requiredTerms: ["2.99% foreign exchange fee"] },
      { fieldKey: "atm_fee", displayValue: "1% plus possible ATM operator fee", valueJson: { rate: 1, unit: "percent" }, scopeJson: { physicalCardOnly: true, operatorFeeMayApply: true }, requiredTerms: ["ATM withdrawal", "1% of the withdrawal amount"] },
      { fieldKey: "spend_limit", displayValue: "A$5,000 daily spend; A$1,000 daily ATM", valueJson: { dailySpend: 5000, dailyAtm: 1000, currency: "AUD" }, scopeJson: { country: "AU" }, requiredTerms: ["Maximum daily spend", "$5000", "Maximum daily ATM withdrawal amount"] },
    ],
  },
  {
    candidateKey: "coinspot-card",
    slug: "coinspot-mastercard-product",
    title: "CoinSpot Mastercard",
    url: "https://www.coinspot.com.au/card",
    authorityTier: "B",
    sourceType: "official issuer product guide",
    facts: [
      { fieldKey: "card_type", displayValue: "Prepaid debit Mastercard", scopeJson: { country: "AU" }, requiredTerms: ["prepaid debit card"] },
      { fieldKey: "annual_fee", displayValue: "Verified explicit zero startup and annual fee", valueJson: { amount: 0, currency: "AUD" }, scopeJson: { country: "AU" }, requiredTerms: ["no startup or annual fees"] },
      { fieldKey: "funding_model", displayValue: "Selected crypto converts to AUD in real time at purchase", scopeJson: { settlementCurrency: "AUD", automaticConversion: true }, requiredTerms: ["instant real-time conversion", "Australian currency"] },
      { fieldKey: "supported_assets", displayValue: "480+ cryptocurrencies; up to five linked wallets", valueJson: { minimumAssetCount: 480, maximumLinkedWallets: 5 }, scopeJson: { exactListInApp: true }, requiredTerms: ["480+ cryptocurrencies", "up to five wallets"] },
      { fieldKey: "mobile_wallet", displayValue: "Apple Pay and Google Pay", scopeJson: { contactless: true }, requiredTerms: ["Apple Pay", "Google Pay"] },
      { fieldKey: "eligibility", displayValue: "Fully verified CoinSpot account with 2FA", scopeJson: { country: "AU", kyc: true, twoFactorRequired: true }, requiredTerms: ["fully verified CoinSpot account", "2FA enabled"] },
    ],
  },
  {
    candidateKey: "coinzoom-card",
    slug: "coinzoom-prime-card-rewards-2026",
    title: "CoinZoom card spending rewards",
    url: "https://support.coinzoom.com/en/articles/12821905-how-to-earn-rewards-on-everyday-purchases",
    authorityTier: "B",
    sourceType: "official issuer membership and reward guide",
    facts: [
      { fieldKey: "prime_level_none", displayValue: "Non-Prime: 0 ZOOM; 0.5%", valueJson: { name: "Non-Prime", zoomRequired: 0, rewardPercent: 0.5, tierOrder: 1 }, scopeJson: { dimension: "membership_level" }, requiredTerms: ["Non-Prime (Green)", "0.5%", "0"] },
      { fieldKey: "prime_level_silver", displayValue: "Silver: 10,000 ZOOM; 1%", valueJson: { name: "Silver", zoomRequired: 10000, rewardPercent: 1, tierOrder: 2 }, scopeJson: { dimension: "membership_level" }, requiredTerms: ["Silver", "1%", "10,000"] },
      { fieldKey: "prime_level_gold", displayValue: "Gold: 50,000 ZOOM; 2%", valueJson: { name: "Gold", zoomRequired: 50000, rewardPercent: 2, tierOrder: 3 }, scopeJson: { dimension: "membership_level" }, requiredTerms: ["Gold", "2%", "50,000"] },
      { fieldKey: "prime_level_diamond", displayValue: "Diamond: 150,000 ZOOM; 3%", valueJson: { name: "Diamond", zoomRequired: 150000, rewardPercent: 3, tierOrder: 4 }, scopeJson: { dimension: "membership_level" }, requiredTerms: ["Diamond", "3%", "150,000"] },
      { fieldKey: "prime_level_black", displayValue: "Black: 300,000 ZOOM; 5%", valueJson: { name: "Black", zoomRequired: 300000, rewardPercent: 5, tierOrder: 5 }, scopeJson: { dimension: "membership_level" }, requiredTerms: ["Black", "5%", "300,000"] },
      { fieldKey: "reward_currency", displayValue: "ZOOM tokens", valueJson: { asset: "ZOOM" }, scopeJson: { settlementAfterPurchase: true }, requiredTerms: ["form of ZOOM tokens"] },
    ],
  },
  {
    candidateKey: "swissborg-card",
    slug: "swissborg-card-launch-2026",
    title: "The SwissBorg Card Is Here",
    url: "https://swissborg.com/blog/the-swissborg-card-is-here",
    authorityTier: "B",
    sourceType: "official issuer launch and product guide",
    facts: [
      { fieldKey: "card_type", displayValue: "Free virtual Mastercard", valueJson: { fee: 0 }, scopeJson: { physicalCard: "announced, not current" }, requiredTerms: ["Mastercard", "free Virtual Card"] },
      { fieldKey: "funding_model", displayValue: "Real-time crypto-to-fiat conversion at point of sale; no pre-loading", scopeJson: { automaticConversion: true, prefundingRequired: false }, requiredTerms: ["No Pre-loading Required", "real-time crypto-to-fiat conversion"] },
      { fieldKey: "supported_assets", displayValue: "Primary and backup crypto funds; exact available list is in app", scopeJson: { multiAsset: true, exactListInApp: true }, requiredTerms: ["Multi-Asset Support", "Backup Funds"] },
      { fieldKey: "reward", displayValue: "Up to 99% of exchange fees returned in BORG, based on Loyalty Rank", valueJson: { maximumFeeCashbackPercent: 99, rewardAsset: "BORG" }, scopeJson: { dimension: "loyalty_rank", notPurchaseCashbackPercent: true }, requiredTerms: ["up to 99%", "BORG"] },
      { fieldKey: "eligibility_scope", displayValue: "Phased rollout across 30 countries, mainly EEA and Switzerland", valueJson: { statedCountryCount: 30 }, scopeJson: { phasedRollout: true, ukAnnouncedLater: true }, requiredTerms: ["30 countries", "EEA and Switzerland"] },
      { fieldKey: "mobile_wallet", displayValue: "Google Pay; Apple Pay phased rollout", scopeJson: { googlePay: true, applePay: "phased rollout" }, requiredTerms: ["Apple Pay", "Google Pay"] },
    ],
  },
  {
    candidateKey: "mexc-card",
    slug: "mexc-card-product-2026",
    title: "MEXC Card",
    url: "https://www.mexc.com/en-GB/buy-crypto/mexc-card",
    authorityTier: "B",
    sourceType: "official issuer regional plan and reward guide",
    facts: [
      { fieldKey: "reward_tier_standard", displayValue: "Standard: M-Score 350–599; 4%; 100 USDT cap", valueJson: { name: "Standard", mScoreMinimum: 350, mScoreMaximum: 599, rewardPercent: 4, monthlyCap: 100, capCurrency: "USDT", tierOrder: 1 }, scopeJson: { dimension: "reward_tier" }, requiredTerms: ["Standard", "350 - 599", "4%"] },
      { fieldKey: "reward_tier_premier", displayValue: "Premier: M-Score 600–799; 6%; 300 USDT cap", valueJson: { name: "Premier", mScoreMinimum: 600, mScoreMaximum: 799, rewardPercent: 6, monthlyCap: 300, capCurrency: "USDT", tierOrder: 2 }, scopeJson: { dimension: "reward_tier" }, requiredTerms: ["Premier", "600 - 799", "6%"] },
      { fieldKey: "reward_tier_elite", displayValue: "Elite: M-Score 800+; 10%; 800 USDT cap", valueJson: { name: "Elite", mScoreMinimum: 800, rewardPercent: 10, monthlyCap: 800, capCurrency: "USDT", tierOrder: 3 }, scopeJson: { dimension: "reward_tier" }, requiredTerms: ["Elite", "800 +", "10%"] },
      { fieldKey: "funding_model", displayValue: "USDT transferred to Fiat account funds the card", scopeJson: { asset: "USDT", account: "Fiat" }, requiredTerms: ["transferring USDT to your Fiat account"] },
      { fieldKey: "kyc", displayValue: "Advanced KYC required", scopeJson: { verificationLevel: "Advanced" }, requiredTerms: ["Advanced KYC"] },
      { fieldKey: "mobile_wallet", displayValue: "Apple Wallet and Google Wallet", scopeJson: { contactless: true }, requiredTerms: ["Apple Wallet", "Google Wallet"] },
    ],
  },
  {
    candidateKey: "kolo-card",
    slug: "kolo-card-product",
    title: "Kolo Crypto Card",
    url: "https://kolo.xyz/",
    authorityTier: "B",
    sourceType: "official issuer product guide",
    facts: [
      { fieldKey: "reward", displayValue: "2% cashback in Bitcoin", valueJson: { rewardPercent: 2, rewardAsset: "BTC" }, scopeJson: { currentHomepageClaim: true, exactDurationRequiresReview: true }, requiredTerms: ["2% in Bitcoin"] },
      { fieldKey: "network", displayValue: "Visa or Mastercard, depending on issued card", scopeJson: { networkVaries: true }, requiredTerms: ["Visa or Mastercard"] },
      { fieldKey: "supported_assets", displayValue: "Crypto top-ups include BTC, ETH, LTC, USDT, and other assets", valueJson: { examples: ["BTC", "ETH", "LTC", "USDT"] }, scopeJson: { examplesNotExhaustive: true }, requiredTerms: ["BTC", "ETH", "LTC", "USDT"] },
    ],
  },
  {
    candidateKey: "mercuryo-spend",
    slug: "mercuryo-spend-card-launch",
    title: "Mercuryo launches Spend Card",
    url: "https://mercuryo.io/explore/announcements/cryptopowered-freedom-starts-with-spend-mercuryo-launches-spend-card-compatible-with-ledger",
    authorityTier: "B",
    sourceType: "official issuer product announcement",
    facts: [
      { fieldKey: "card_type", displayValue: "Mastercard crypto debit card", scopeJson: { product: "Spend", ledgerCompatible: true }, requiredTerms: ["Mastercard crypto debit card", "LEDGER"] },
      { fieldKey: "issuance_fee", displayValue: "Verified explicit zero", valueJson: { amount: 0 }, scopeJson: { product: "Spend" }, requiredTerms: ["no issuance fee"] },
    ],
  },
];
