import type { OfficialSourceDefinition } from "./priority-official-sources";

/**
 * Official evidence for legacy catalog candidates that still lacked a
 * verified source. Facts remain review-pending until normalization and
 * independent approval; legal terms override conflicting marketing copy.
 */
export const remainingCatalogSources: OfficialSourceDefinition[] = [
  {
    candidateKey: "bitgetwallet-card",
    slug: "bitget-wallet-card-2026",
    title: "Bitget Wallet Card",
    url: "https://web3.bitget.com/card",
    authorityTier: "B",
    sourceType: "official issuer product, fee, and eligibility guide",
    facts: [
      { fieldKey: "network", displayValue: "Debit Mastercard on the current product page; network can vary with the regional issuing partner", scopeJson: { network: "Mastercard", regionalPartnerMayVary: true }, requiredTerms: ["Debit Mastercard", "Depending on your region's card issuing partner"] },
      { fieldKey: "eligibility_scope", displayValue: "Available in listed EEA/UK, Latin American, APAC, and China markets", scopeJson: { regions: ["EEA", "GB", "LATAM", "APAC", "CN"], exactCountryListInSource: true }, requiredTerms: ["Europe (EEA and UK)", "Latin American countries", "APAC", "China"] },
      { fieldKey: "supported_assets", displayValue: "Crypto top-up includes USDT and USDC; exact token availability is regional", valueJson: { examples: ["USDT", "USDC"] }, scopeJson: { examplesNotExhaustive: true, regionSpecific: true }, requiredTerms: ["USDT and USDC"] },
      { fieldKey: "zero_fee_quota", displayValue: "Within the monthly quota, FX, top-up, and conversion fees are refunded; this is a reimbursement, not an unconditional zero fee", scopeJson: { monthlyQuota: true, mechanism: "fee refund", exactQuotaRequiresCurrentRegionalSource: true }, requiredTerms: ["monthly 0-Fee quota", "fully fee-refunded", "FX fees, top-up fees, and conversion fees"] },
      { fieldKey: "fees_above_quota", displayValue: "Above the monthly quota, regional/card fees are typically 1% to 2.2% per transaction", valueJson: { typicalMinimumPercent: 1, typicalMaximumPercent: 2.2 }, scopeJson: { regionAndCardTypeSensitive: true, notGuaranteedRange: true }, requiredTerms: ["typically ranging from 1% to 2.2%"] },
      { fieldKey: "mobile_wallet", displayValue: "Apple Pay, Google Pay, WeChat Pay, and Alipay are supported", valueJson: { wallets: ["Apple Pay", "Google Pay", "WeChat Pay", "Alipay"] }, scopeJson: { regionalAvailabilityMayVary: true }, requiredTerms: ["Apple Pay", "Google Pay", "WeChat Pay", "Alipay"] },
    ],
  },
  {
    candidateKey: "bitrefill-card",
    slug: "bitrefill-card-spending-tiers-2026",
    title: "Bitrefill Card spending limits",
    url: "https://help.bitrefill.com/hc/en-us/articles/15050315508882-What-are-the-spending-limits-for-the-Bitrefill-Card",
    authorityTier: "B",
    sourceType: "official issuer verification-tier and limit guide",
    facts: [
      { fieldKey: "card_plans", displayValue: "One Bitrefill Card program with Starter and Plus verification tiers", valueJson: { plans: ["Starter", "Plus"] }, scopeJson: { dimension: "verification_level", separateCatalogCards: false }, requiredTerms: ["two spending limit tiers", "Starter", "Plus"] },
      { fieldKey: "starter_limit", displayValue: "Starter permits up to €15,000 in deposits and spending with identity verification", valueJson: { statedLimitEur: 15000 }, scopeJson: { dimension: "verification_level", plan: "Starter", exactPeriodNotAsserted: true }, requiredTerms: ["15,000 EUR", "only identity verification"] },
      { fieldKey: "plus_verification", displayValue: "Plus requires additional identity and address verification and provides higher limits", scopeJson: { dimension: "verification_level", plan: "Plus", exactMatrixRequiresPricingSource: true }, requiredTerms: ["additional identity and address verification", "higher spending capabilities"] },
    ],
  },
  {
    candidateKey: "bitrefill-card",
    slug: "bitrefill-card-atm-fee-2026",
    title: "Bitrefill Card ATM fee",
    url: "https://help.bitrefill.com/hc/en-us/articles/24791875786002-Is-there-a-fee-for-ATM-withdrawals",
    authorityTier: "B",
    sourceType: "official issuer ATM fee guide",
    facts: [
      { fieldKey: "atm_fee", displayValue: "ATM withdrawals cost 2.49%", valueJson: { feePercent: 2.49 }, scopeJson: { operatorFeeMayAlsoApply: true }, requiredTerms: ["2.49% fee for ATM withdrawals"] },
    ],
  },
  {
    candidateKey: "bitrefill-card",
    slug: "bitrefill-card-cashback-2026",
    title: "Bitrefill Card cashback",
    url: "https://help.bitrefill.com/hc/en-us/articles/31491398773010-How-do-I-earn-Bitrefill-Card-cashback",
    authorityTier: "B",
    sourceType: "official issuer reward guide",
    facts: [
      { fieldKey: "reward", displayValue: "1% on crypto deposits and 1% on card spending; reward is credited to a separate cashback balance", valueJson: { cryptoDepositPercent: 1, cardSpendPercent: 1 }, scopeJson: { notAdditiveOnSinglePurchase: true, redemptionTermsSeparate: true }, requiredTerms: ["deposit cryptocurrency", "1% cashback", "spend with your Bitrefill Card", "Cashback balance"] },
    ],
  },
  {
    candidateKey: "bleap-card",
    slug: "bleap-cashback-terms-2026",
    title: "Bleap Cashback Terms and Conditions",
    url: "https://www.bleap.finance/legal-agreements/cashback-terms-and-conditions",
    authorityTier: "A",
    sourceType: "official legal cashback terms",
    facts: [
      { fieldKey: "reward_default", displayValue: "Current default cashback is 1% on up to €500 per transaction and €3,000 monthly eligible spend", valueJson: { rewardPercent: 1, transactionEligibleSpendCapEur: 500, monthlyEligibleSpendCapEur: 3000 }, scopeJson: { effectiveFrom: "2026-02-12", noPublishedEndDate: true }, requiredTerms: ["Default Cashback", "1%", "Limit per transaction", "500€", "3000€"] },
      { fieldKey: "reward_transport_delivery", displayValue: "3% on named transportation and delivery merchants, with merchant-specific fair-usage caps", valueJson: { rewardPercent: 3 }, scopeJson: { categories: ["Transportation", "Delivery"], namedMerchantsOnly: true, capsApplyPerService: true }, requiredTerms: ["Transportation", "Delivery", "3%", "Applies separately to each listed service"] },
      { fieldKey: "benefit_subscriptions", displayValue: "20% on named streaming, AI, and gaming subscriptions, each with published monthly or annual eligible-spend caps", valueJson: { rewardPercent: 20, categories: ["Streaming", "AI", "Gaming"] }, scopeJson: { namedMerchantsOnly: true, merchantSpecificCaps: true }, requiredTerms: ["Subscriptions (Streaming)", "Subscriptions (AI)", "Subscriptions (Gaming)", "Claude", "ChatGPT", "Gemini"] },
      { fieldKey: "expired_restaurant_promotion", displayValue: "The 2% restaurant and supermarket promotion ended 31 May 2026 and must not be shown as current", valueJson: { rewardPercent: 2, endDate: "2026-05-31" }, scopeJson: { lifecycle: "EXPIRED", publishAsCurrent: false, legalTermsOverrideMarketing: true }, requiredTerms: ["Restaurants, Supermarkets", "31/05/2026"] },
      { fieldKey: "reward_settlement", displayValue: "Cashback is automatically credited in USDC after an eligible transaction settles", valueJson: { rewardAsset: "USDC" }, scopeJson: { activationRequired: false, settlementRequired: true }, requiredTerms: ["credited in USDC", "earned automatically"] },
    ],
  },
  {
    candidateKey: "brighty-card",
    slug: "brighty-card-reward-terms-2026",
    title: "Brighty Payment Cards Reward terms",
    url: "https://brighty.app/en/updated-earning-and-payment-card-terms-and-conditions",
    authorityTier: "A",
    sourceType: "official legal payment-card reward terms",
    facts: [
      { fieldKey: "reward_mechanism", displayValue: "Stablecoin balance linked to the card earns daily rewards paid into the Rewards Box in USDC", valueJson: { rewardAsset: "USDC", accrual: "daily" }, scopeJson: { linkedAssets: ["USDC", "EURT", "EURC", "EURA"] }, requiredTerms: ["linked to stablecoin accounts", "earns daily rewards", "deposited in USDC", "Rewards Box"] },
      { fieldKey: "subscription_dependency", displayValue: "The earning rate depends on the Brighty subscription plan; the legal page does not publish a fixed tier matrix", scopeJson: { dimension: "subscription", exactPublicRateUnknown: true, doNotConvertUnknownToZero: true }, requiredTerms: ["subject to change based on your Subscription Plan"] },
    ],
  },
  {
    candidateKey: "coca-card",
    slug: "coca-membership-rewards-2026",
    title: "COCA membership and rewards",
    url: "https://docs.coca.xyz/coca/membership-and-rewards",
    authorityTier: "B",
    sourceType: "official issuer membership and reward guide",
    facts: [
      { fieldKey: "membership_tiers", displayValue: "One COCA Card program with Starter, Standard, Standard+, Premium, Premium+, and Elite membership tiers", valueJson: { tiers: ["Starter", "Standard", "Standard+", "Premium", "Premium+", "Elite"] }, scopeJson: { dimension: "membership_level", separateCatalogCards: false }, requiredTerms: ["Starter", "Standard+", "Premium+", "Elite"] },
      { fieldKey: "tier_matrix", displayValue: "Starter 1% unlimited; Standard 3% on first $1,000; Standard+ 4% on $1,750; Premium 5% on $2,500; Premium+ 6% on $5,000; Elite 8% on $10,000; capped tiers fall to 1%", valueJson: { Starter: { cocaStaked: 0, rewardPercent: 1, eligibleSpendCap: null }, Standard: { cocaStaked: 300, rewardPercent: 3, eligibleSpendCap: 1000 }, "Standard+": { cocaStaked: 1000, rewardPercent: 4, eligibleSpendCap: 1750 }, Premium: { cocaStaked: 3000, rewardPercent: 5, eligibleSpendCap: 2500 }, "Premium+": { cocaStaked: 10000, rewardPercent: 6, eligibleSpendCap: 5000 }, Elite: { cocaStaked: 30000, rewardPercent: 8, eligibleSpendCap: 10000 }, afterCapPercent: 1 }, scopeJson: { dimension: "membership_level", qualification: "COCA staked", period: "month" }, requiredTerms: ["1% unlimited", "3% on first $1,000/mo", "4% on first $1,750/mo", "5% on first $2,500/mo", "6% on first $5,000/mo", "8% on first $10,000/mo"] },
      { fieldKey: "subscription_rebates", displayValue: "Membership tiers include zero to four eligible subscription rebates at 50%", valueJson: { Starter: 0, Standard: 1, "Standard+": 2, Premium: 2, "Premium+": 3, Elite: 4, rebatePercent: 50 }, scopeJson: { dimension: "membership_level", eligibleServicesOnly: true }, requiredTerms: ["Subscriptions included", "50%-off subscriptions"] },
      { fieldKey: "cooldown", displayValue: "Cancelling a tier starts a 30-day cooldown; benefits continue during it before returning to Starter", valueJson: { cooldownDays: 30, fallbackTier: "Starter" }, scopeJson: { dimension: "membership_level" }, requiredTerms: ["30-day cooldown", "drop back to Starter"] },
    ],
  },
  {
    candidateKey: "cypher-card",
    slug: "cypher-wind-down-2026",
    title: "Cypher wind-down timeline",
    url: "https://cypherhq.io/wind-down-support/what-is-happening-to-cypher/",
    authorityTier: "A",
    sourceType: "official lifecycle and shutdown notice",
    facts: [
      { fieldKey: "lifecycle", displayValue: "SUNSETTING: new applications and issuance ended 8 July 2026; all cards stop 7 August; platform closes 6 September", valueJson: { lifecycle: "SUNSETTING", issuanceEnded: "2026-07-08", cardSpendingEnds: "2026-08-07", platformEnds: "2026-09-06" }, scopeJson: { publishAsAvailable: false, currentCardholdersOnlyUntilSpendEnd: true }, requiredTerms: ["Cypher is sunsetting", "July 8, 2026", "August 7, 2026", "September 6, 2026"] },
      { fieldKey: "reward_status", displayValue: "The final reward distribution was 16 July 2026; no further rewards are distributed", valueJson: { finalDistributionDate: "2026-07-16" }, scopeJson: { lifecycle: "ENDED", publishAsCurrent: false }, requiredTerms: ["final rewards cycle", "No further reward distributions"] },
      { fieldKey: "acquisition", displayValue: "Cypher was acquired by Nium; a future product is being rebuilt and is not the current card", scopeJson: { acquirer: "Nium", futureProductUnspecified: true }, requiredTerms: ["acquired by Nium", "next version of Cypher"] },
    ],
  },
  {
    candidateKey: "fiat24-card",
    slug: "fiat24-individual-pricing-2026",
    title: "Fiat24 pricing for individuals",
    url: "https://docs.fiat24.com/products/pricing-for-individuals",
    authorityTier: "B",
    sourceType: "official provider account-tier and fee guide",
    facts: [
      { fieldKey: "account_tiers", displayValue: "Standard, Premium, and Ultimate account tiers determine the associated debit card and top-up fee", valueJson: { tiers: ["Standard", "Premium", "Ultimate"] }, scopeJson: { dimension: "account_tier", cardPlanDerivedFromAccount: true, separateCatalogCards: false }, requiredTerms: ["Standard Debit Card", "Premium Debit Card", "Ultimate Debit Card"] },
      { fieldKey: "standard", displayValue: "Standard: free 8-digit NFT or 1 F24 for 5/6 digits; $30,000 monthly limit; 1% crypto top-up", valueJson: { monthlyLimitUsd: 30000, cryptoTopupPercent: 1, freeEightDigitNft: true, fiveSixDigitMintF24: 1 }, scopeJson: { dimension: "account_tier", tier: "Standard", observedCurrentPageNotSearchCache: true }, requiredTerms: ["8 digits NFT", "FREE", "$30,000/Mth limit", "1.0% Crypto topup fee"] },
      { fieldKey: "premium", displayValue: "Premium: 4-digit NFT; 1,500 F24 mint; $30,000 monthly limit; 0.5% crypto top-up", valueJson: { nftDigits: 4, mintF24: 1500, monthlyLimitUsd: 30000, cryptoTopupPercent: 0.5 }, scopeJson: { dimension: "account_tier", tier: "Premium", observedCurrentPageNotSearchCache: true }, requiredTerms: ["4 digits NFT", "1,500 F24 mint fee", "$30,000/Mth limit", "0.5% Crypto topup fee"] },
      { fieldKey: "ultimate", displayValue: "Ultimate: 3-digit NFT; 15,000 F24 mint; $30,000 monthly limit; 0.25% crypto top-up", valueJson: { nftDigits: 3, mintF24: 15000, monthlyLimitUsd: 30000, cryptoTopupPercent: 0.25 }, scopeJson: { dimension: "account_tier", tier: "Ultimate", observedCurrentPageNotSearchCache: true }, requiredTerms: ["3 digits NFT", "15,000 F24 mint fee", "$30,000/Mth limit", "0.25% crypto topup fee"] },
    ],
  },
  {
    candidateKey: "fold-card",
    slug: "fold-pricing-2026",
    title: "Fold pricing and card products",
    url: "https://foldapp.com/pricing",
    authorityTier: "B",
    sourceType: "official product, subscription, and reward guide",
    facts: [
      { fieldKey: "product_boundary", displayValue: "Fold Debit and Fold Bitcoin Credit Card are separate products with different issuers and economics", valueJson: { products: [{ name: "Fold Debit Card", issuer: "Sutton Bank" }, { name: "Fold Bitcoin Credit Card", issuer: "Celtic Bank" }] }, scopeJson: { canonicalProgramsMustBeSeparate: true }, requiredTerms: ["Fold Debit Card", "Sutton Bank", "Fold Bitcoin Credit Card", "Celtic Bank"] },
      { fieldKey: "debit_subscriptions", displayValue: "Debit membership is free; Fold+ costs $10 monthly or $100 annually", valueJson: { Member: { monthlyFee: 0 }, "Fold+": { monthlyFee: 10, annualFee: 100 } }, scopeJson: { product: "Fold Debit Card", dimension: "subscription" }, requiredTerms: ["Fold Member", "Free", "Fold+ Members", "$10", "$100 a year"] },
      { fieldKey: "debit_rewards", displayValue: "Fold+ debit benefits include up to 1.5% ACH bill pay, up to 15% merchant boosts, 1.5% categories, and 0.5% other eligible purchases", valueJson: { achBillPayMaximumPercent: 1.5, merchantBoostMaximumPercent: 15, categoryPercent: 1.5, otherPercent: 0.5 }, scopeJson: { product: "Fold Debit Card", subscription: "Fold+", offerAndEligibilityTermsApply: true }, requiredTerms: ["Up to 1.5% back with ACH bill pay rewards", "up to 15% back on merchant boosts", "0.5% on all other eligible purchases"] },
      { fieldKey: "credit_rewards", displayValue: "Credit card earns 1.5% BTC uncapped; recurring/direct-to-bitcoin and BTC statement-payment bonuses can raise the first $2,000 monthly spend to at most 4%", valueJson: { basePercent: 1.5, baseCap: null, bonusEligibleMonthlySpendUsd: 2000, maximumPercent: 4 }, scopeJson: { product: "Fold Bitcoin Credit Card", bonusConditionsApply: true }, requiredTerms: ["earn 1.5% back in bitcoin", "first $2,000 in monthly purchases", "maximum potential rate of 4%"] },
      { fieldKey: "credit_annual_fee", displayValue: "Fold Bitcoin Credit Card has no annual fee", valueJson: { annualFeeUsd: 0 }, scopeJson: { product: "Fold Bitcoin Credit Card" }, requiredTerms: ["There is no annual fee"] },
    ],
  },
  {
    candidateKey: "gemini-card",
    slug: "gemini-credit-card-2026",
    title: "Gemini Credit Card",
    url: "https://www.gemini.com/credit-card",
    authorityTier: "B",
    sourceType: "official credit-card product and reward guide",
    facts: [
      { fieldKey: "reward_tiers", displayValue: "4% on gas, EV, and transit up to $300 monthly then 1%; 3% dining; 2% groceries; 1% elsewhere", valueJson: { gasEvTransit: { percent: 4, monthlySpendCapUsd: 300, afterCapPercent: 1 }, diningPercent: 3, groceriesPercent: 2, otherPercent: 1 }, scopeJson: { dimension: "reward_category", optionNames: ["Gas, EV, and transit", "Dining", "Groceries", "Other purchases"], qualifyingPurchasesOnly: true }, requiredTerms: ["Gas, EV & Transit", "4%", "Dining", "3%", "Groceries", "2%", "Everything else", "1%"] },
      { fieldKey: "fees", displayValue: "No annual fee and no foreign transaction fee", valueJson: { annualFeeUsd: 0, foreignTransactionFeePercent: 0 }, scopeJson: { creditTermsAndApprovalApply: true }, requiredTerms: ["No annual fee", "No foreign transaction fees"] },
      { fieldKey: "reward_asset", displayValue: "Rewards can be Bitcoin or more than 50 supported cryptocurrencies and are generally deposited instantly", scopeJson: { assetChoiceCountMinimum: 51, postingExceptionsApply: true }, requiredTerms: ["Earn bitcoin, or 50+ cryptos", "Rewards are instantly deposited"] },
      { fieldKey: "network_issuer", displayValue: "Mastercard World Elite issued by WebBank", valueJson: { network: "Mastercard World Elite", issuer: "WebBank" }, scopeJson: { country: "US", product: "consumer credit card" }, requiredTerms: ["Mastercard", "issued by WebBank"] },
    ],
  },
  {
    candidateKey: "oobit-card",
    slug: "oobit-reward-terms-2026",
    title: "Oobit 5X Reward Terms",
    url: "https://www.oobit.com/legal/5x-reward-terms",
    authorityTier: "A",
    sourceType: "official legal loyalty and reward terms",
    facts: [
      { fieldKey: "reward_levels", displayValue: "Five Tap to Pay loyalty levels: 1x at $0, 2x at $250, 3x at $500, 4x at $1,000, and 5x at $1,500 cumulative spend", valueJson: { levels: [{ name: "Level 1", thresholdUsd: 0, pointsPerUsd: 1 }, { name: "Level 2", thresholdUsd: 250, pointsPerUsd: 2 }, { name: "Level 3", thresholdUsd: 500, pointsPerUsd: 3 }, { name: "Level 4", thresholdUsd: 1000, pointsPerUsd: 4 }, { name: "Level 5", thresholdUsd: 1500, pointsPerUsd: 5 }] }, scopeJson: { dimension: "loyalty_tier", qualificationWindowDays: 90 }, requiredTerms: ["Level 1", "Level 5", "1,500", "5x", "90-day cycle"] },
      { fieldKey: "points_value", displayValue: "1,000 points convert to $1 in USDC for EEA users or USDT elsewhere; converted rewards are spend-only in Tap to Pay", valueJson: { pointsPerUsd: 1000, eeaAsset: "USDC", otherAsset: "USDT" }, scopeJson: { withdrawalAllowed: false, transferAllowed: false, use: "Tap to Pay only" }, requiredTerms: ["1,000 points to USD 1", "European Economic Area", "USDC", "USDT", "cannot be withdrawn"] },
      { fieldKey: "stablecoin_reward", displayValue: "Eligible USDT, USDR, or EURR payments can receive 5% on at most $200 eligible spend", valueJson: { rewardPercent: 5, eligibleSpendCapUsd: 200, assets: ["USDT", "USDR", "EURR"] }, scopeJson: { offerTermsMayChange: true }, requiredTerms: ["Stablecoin Rewards", "5%", "USD 200"] },
      { fieldKey: "token_reward", displayValue: "Eligible OOB payments can receive 10% on at most $10,000 eligible spend", valueJson: { rewardPercent: 10, eligibleSpendCapUsd: 10000, asset: "OOB" }, scopeJson: { offerTermsMayChange: true }, requiredTerms: ["Token Rewards", "10%", "USD 10,000"] },
    ],
  },
  {
    candidateKey: "safepal-card",
    slug: "safepal-banking-gateway-2026",
    title: "SafePal Banking Gateway",
    url: "https://www.safepal.com/en/bank",
    authorityTier: "B",
    sourceType: "official wallet co-brand product and fee guide",
    facts: [
      { fieldKey: "provider_relationship", displayValue: "SafePal provides the wallet interface; Fiat24 provides the regulated Swiss IBAN and card service", valueJson: { interface: "SafePal", provider: "Fiat24" }, scopeJson: { coBrand: true, canonicalProviderRelationshipRequired: true }, requiredTerms: ["offered in collaboration with Fiat24", "Swiss IBAN"] },
      { fieldKey: "card_type", displayValue: "Virtual Mastercard debit card", valueJson: { form: "virtual", network: "Mastercard", type: "debit" }, scopeJson: { provider: "Fiat24" }, requiredTerms: ["virtual Master debit cards"] },
      { fieldKey: "account_fees", displayValue: "No account setup or management fee; transfer, swap, top-up, spread, and third-party charges can still apply", valueJson: { setupFee: 0, managementFee: 0 }, scopeJson: { notAllOperationsFree: true }, requiredTerms: ["Zero fees for account setup and management", "Crypto swap fees", "account top-up", "spread"] },
      { fieldKey: "topup_fee", displayValue: "Advertised crypto top-up can be as low as 0.4% at the highest account tier; this is not a universal rate", valueJson: { advertisedMinimumPercent: 0.4 }, scopeJson: { dimension: "account_tier", highestTierOnly: true, exactTierMatrixNotPublicOnPage: true }, requiredTerms: ["rates as low as 0.4%", "highest account tier"] },
      { fieldKey: "qualification", displayValue: "No credit check or mandatory staking for basic eligibility; KYC is required", scopeJson: { mandatoryStakingForEligibility: false, kycRequired: true }, requiredTerms: ["No credit checks or mandatory staking", "KYC"] },
      { fieldKey: "mobile_wallet", displayValue: "PayPal, Apple Pay, Google Pay, and Samsung Pay are supported", valueJson: { wallets: ["PayPal", "Apple Pay", "Google Pay", "Samsung Pay"] }, scopeJson: { regionMayVary: true }, requiredTerms: ["Paypal", "Apple Pay", "Google Pay", "Samsung Pay"] },
    ],
  },
  {
    candidateKey: "tokenpocket-card",
    slug: "tokenpocket-card-fees-2026",
    title: "TokenPocket Card fees",
    url: "https://help.tokenpocket.pro/en/wallet-operation/tp-card/detailed-tp-card-fees",
    authorityTier: "B",
    sourceType: "official wallet co-brand fee and limit guide",
    facts: [
      { fieldKey: "minting_fee", displayValue: "0.002 ETH NFT minting fee on Arbitrum; the wallet should hold at least 0.01 ETH", valueJson: { mintingFeeEth: 0.002, recommendedMinimumBalanceEth: 0.01 }, scopeJson: { network: "Arbitrum One", earlyUserRefundMayApply: true }, requiredTerms: ["0.002 ETH", "Minimum 0.01 ETH", "Arbitrum One"] },
      { fieldKey: "topup_fee", displayValue: "0.5% to 1% top-up fee, with invitation-based discounts", valueJson: { minimumPercent: 0.5, maximumPercent: 1 }, scopeJson: { referralDiscountMayApply: true }, requiredTerms: ["Top-Up Fee", "0.5% - 1%", "Discount depends"] },
      { fieldKey: "card_fees", displayValue: "No purchase transaction fee and no annual fee", valueJson: { transactionFeePercent: 0, annualFee: 0 }, scopeJson: { issuerOrNetworkExceptionsNotAsserted: true }, requiredTerms: ["No transaction fees", "No Annual Fee"] },
      { fieldKey: "regular_limit", displayValue: "Regular TP Card monthly limit is $100,000", valueJson: { monthlyLimitUsd: 100000 }, scopeJson: { plan: "Regular", dimension: "card_plan" }, requiredTerms: ["Regular TP Card Users", "$100,000/month"] },
      { fieldKey: "premium_announced", displayValue: "Premium plan with $500,000 to $50,000,000 monthly limits is announced as coming soon, not current", valueJson: { monthlyLimitMinimumUsd: 500000, monthlyLimitMaximumUsd: 50000000 }, scopeJson: { plan: "Premium", dimension: "card_plan", lifecycle: "ANNOUNCED", publishAsCurrent: false }, requiredTerms: ["Premium TP Card Users", "Premium plan coming soon"] },
    ],
  },
  {
    candidateKey: "imtoken-card",
    slug: "imtoken-fiat24-card-2026",
    title: "imToken Card powered by Fiat24",
    url: "https://support.token.im/hc/en-us/articles/42087086799897-imToken-Card-Fiat24-is-Here-Easy-Application-No-Hassles",
    authorityTier: "B",
    sourceType: "official wallet co-brand product and fee guide",
    facts: [
      { fieldKey: "product_boundary", displayValue: "The current Fiat24 Mastercard debit product replaces a separate retired DCS co-branded credit card", scopeJson: { currentProvider: "Fiat24", retiredProvider: "DCS", canonicalProgramsMustNotMerge: true }, requiredTerms: ["Fiat24", "Mastercard debit card", "DCS-issued card", "has been retired"] },
      { fieldKey: "currencies_assets", displayValue: "Supports USD, EUR, CHF, and RMB, with USDC, USDT, ETH, and WBTC top-ups on Arbitrum", valueJson: { currencies: ["USD", "EUR", "CHF", "RMB"], topupAssets: ["USDC", "USDT", "ETH", "WBTC"], network: "Arbitrum" }, scopeJson: { exactAvailabilityMayChange: true }, requiredTerms: ["USD, EUR, CHF, RMB", "USDC, USDT, ETH, WBTC"] },
      { fieldKey: "fees", displayValue: "0.0015 ETH NFT minting and 1% token top-up; no annual, FX, conversion, fiat-deposit, or card-payment fee", valueJson: { mintingFeeEth: 0.0015, tokenTopupPercent: 1, annualFee: 0, fxFeePercent: 0, conversionFeePercent: 0, fiatDepositFeePercent: 0, transactionFeePercent: 0 }, scopeJson: { additionalSettlementAndRateChargesMayApply: true }, requiredTerms: ["0.0015 ETH", "1% fee for token top-ups", "no foreign exchange fees", "no annual fee"] },
      { fieldKey: "mobile_wallet", displayValue: "Apple Pay, Google Pay, Samsung Pay, WeChat Pay, and Alipay are supported", valueJson: { wallets: ["Apple Pay", "Google Pay", "Samsung Pay", "WeChat Pay", "Alipay"] }, scopeJson: { regionalAvailabilityMayVary: true }, requiredTerms: ["Apple Pay", "Google Pay", "Samsung Pay", "WeChat Pay", "Alipay"] },
      { fieldKey: "future_rebate", displayValue: "A rebate plan is announced for the future and must not be shown as current", scopeJson: { lifecycle: "ANNOUNCED", publishAsCurrent: false }, requiredTerms: ["launching a rebate plan soon"] },
    ],
  },
  {
    candidateKey: "tria-card",
    slug: "tria-cashback-terms-2026",
    title: "Tria Cashback Terms and Conditions",
    url: "https://docs.tria.so/card-cashback-terms",
    authorityTier: "A",
    sourceType: "official legal card-tier and cashback terms",
    facts: [
      { fieldKey: "card_tiers", displayValue: "Virtual, Signature, and Premium cards are one account-level membership ladder", valueJson: { tiers: ["Virtual", "Signature", "Premium"] }, scopeJson: { dimension: "card_plan", separateCatalogCards: false, accountLevel: true }, requiredTerms: ["Virtual Card", "Signature Card", "Premium Card", "Membership Tier"] },
      { fieldKey: "current_tier_matrix", displayValue: "From 1 June 2026: Virtual 1.5% on $100 then 0.5%; Signature 4.5% on $1,000 then 1%; Premium 6% on $2,000 then 1%", valueJson: { Virtual: { rewardPercent: 1.5, monthlyEligibleSpendCapUsd: 100, afterCapPercent: 0.5 }, Signature: { rewardPercent: 4.5, monthlyEligibleSpendCapUsd: 1000, afterCapPercent: 1 }, Premium: { rewardPercent: 6, monthlyEligibleSpendCapUsd: 2000, afterCapPercent: 1 } }, scopeJson: { dimension: "card_plan", effectiveFrom: "2026-06-01", eligibleSpendOnly: true }, requiredTerms: ["New Program Period", "Virtual Card", "USD 100", "Signature Card", "USD 1,000", "Premium Card", "USD 2,000"] },
      { fieldKey: "highest_tier_rule", displayValue: "If an account holds multiple card types, the highest tier applies to aggregate eligible spend across all cards", scopeJson: { accountLevel: true, hierarchy: ["Premium", "Signature", "Virtual"] }, requiredTerms: ["highest Card type held", "aggregate Eligible Spend across all Cards"] },
      { fieldKey: "reward_asset", displayValue: "Cashback is distributed in eligible stablecoins, currently USDC and/or USDT", valueJson: { assets: ["USDC", "USDT"] }, scopeJson: { providerMayChangeEligibleAssets: true }, requiredTerms: ["Eligible Stablecoins", "USDC and/or USDT"] },
      { fieldKey: "historical_terms", displayValue: "The uncapped 1.5%/4.5%/6% structure ended 31 May 2026 and must not be shown as current", scopeJson: { lifecycle: "HISTORICAL", endDate: "2026-05-31", publishAsCurrent: false }, requiredTerms: ["HISTORICAL PERIOD", "No Monthly Spend Cap", "31 May 2026"] },
    ],
  },
  {
    candidateKey: "tuyo-card",
    slug: "tuyo-card-2026",
    title: "Tuyo Card",
    url: "https://tuyo.com/card",
    authorityTier: "B",
    sourceType: "official card product, fee, and limit guide",
    facts: [
      { fieldKey: "fees", displayValue: "No issuance, monthly, annual, or USD transaction fee; non-USD FX spread up to about 1%", valueJson: { issuanceFee: 0, monthlyFee: 0, annualFee: 0, usdTransactionFeePercent: 0, maximumFxSpreadPercent: 1 }, scopeJson: { networkRateAndRegionalTermsMayApply: true }, requiredTerms: ["no issuance fee", "no monthly fee", "no fee for USD transactions", "up to ~1%"] },
      { fieldKey: "spend_limit", displayValue: "$10,000 daily, with possible increases based on usage", valueJson: { dailyLimitUsd: 10000 }, scopeJson: { mayIncreaseWithUsage: true }, requiredTerms: ["$10,000 per day"] },
      { fieldKey: "funding_asset", displayValue: "USDC on Base; funds can remain in an Earn strategy until spent", valueJson: { asset: "USDC", network: "Base" }, scopeJson: { earnStrategySupported: true }, requiredTerms: ["USDC ON BASE", "keeps earning until you spend"] },
      { fieldKey: "mobile_wallet", displayValue: "Apple Pay and Google Pay", valueJson: { wallets: ["Apple Pay", "Google Pay"] }, scopeJson: { currentMarketingClaim: true }, requiredTerms: ["APPLE PAY & GOOGLE PAY"] },
      { fieldKey: "physical_card", displayValue: "Physical card is announced as coming soon, not current", scopeJson: { lifecycle: "ANNOUNCED", publishAsCurrent: false }, requiredTerms: ["PHYSICAL CARD", "COMING SOON"] },
    ],
  },
  {
    candidateKey: "thorwallet-card",
    slug: "thorwallet-card-plans-2026",
    title: "THORWallet card and account plans",
    url: "https://www.thorwallet.org/",
    authorityTier: "B",
    sourceType: "official wallet card-plan and account-offering guide",
    facts: [
      { fieldKey: "product_dimensions", displayValue: "Basic and Premium are card plans; Swiss Banking is a separate account/card offering; TITN community levels are not card plans", valueJson: { cardPlans: ["Basic", "Premium"], separateOffering: "Swiss Banking", unrelatedDimension: "TITN community tier" }, scopeJson: { doNotFlattenIntoOneTierLadder: true }, requiredTerms: ["Basic", "Premium", "Swiss Banking", "Community Plus"] },
      { fieldKey: "basic_plan", displayValue: "Basic: free virtual USD card, 0% cashback, 1.5% FX, $1 domestic/$5 international ATM, $125,000 monthly limit, 0% top-up", valueJson: { annualFeeUsd: 0, form: "virtual", currency: "USD", rewardPercent: 0, fxPercent: 1.5, domesticAtmUsd: 1, internationalAtmUsd: 5, monthlyLimitUsd: 125000, topupPercent: 0 }, scopeJson: { dimension: "card_plan", plan: "Basic" }, requiredTerms: ["Free forever", "Card type Virtual", "Cashback 0%", "Card FX 1.5%", "$125,000"] },
      { fieldKey: "premium_plan", displayValue: "Premium: $75/year; virtual and physical; up to 2% cashback; 0.5% FX; $5–$15 monthly reward cap; TITN staker boost", valueJson: { annualFeeUsd: 75, forms: ["virtual", "physical"], maximumRewardPercent: 2, fxPercent: 0.5, monthlyRewardCapUsdRange: [5, 15], titnStakerBoost: true }, scopeJson: { dimension: "card_plan", plan: "Premium", exactRewardDependsOnConditions: true }, requiredTerms: ["$6.25", "billed yearly", "Virtual + Physical", "Up to 2%", "Cost / year", "$75", "Max rewards / mo"] },
      { fieldKey: "swiss_banking", displayValue: "Separate free Swiss Banking offering: Swiss IBAN; CHF/EUR/USD/RMB; 1% FX; 0.25%–1% top-up; no cashback; virtual card", valueJson: { annualFeeUsd: 0, currencies: ["CHF", "EUR", "USD", "RMB"], fxPercent: 1, topupPercentRange: [0.25, 1], rewardPercent: 0, form: "virtual" }, scopeJson: { offering: "Swiss Banking", notCardPlan: true }, requiredTerms: ["Swiss IBAN & SEPA", "CHF · EUR · USD · RMB", "Top-up fee 0.25–1%", "Cashback None"] },
      { fieldKey: "community_tiers", displayValue: "Standard, Community, and Community Plus are TITN staking tiers for swap fees and wallet perks, not card tiers", valueJson: { Standard: { titn: 0, swapFeePercent: 1.25 }, Community: { titn: 10000, swapFeePercent: 0.5 }, "Community Plus": { titn: 100000, swapFeePercent: 0.2 } }, scopeJson: { dimension: "loyalty_tier", cardPlan: false }, requiredTerms: ["10,000", "100,000", "Swap fee 0.2%"] },
    ],
  },
  {
    candidateKey: "venmo-card",
    slug: "venmo-credit-card-2026",
    title: "Venmo Credit Card benefits",
    url: "https://venmo.com/about/creditcard/features/visa",
    authorityTier: "B",
    sourceType: "official credit-card product and reward guide",
    facts: [
      { fieldKey: "reward_categories", displayValue: "Automatically earns 3% on the top eligible category, 2% on the next, and 1% on other eligible purchases", valueJson: { topCategoryPercent: 3, secondCategoryPercent: 2, otherPercent: 1 }, scopeJson: { dimension: "reward_category", optionNames: ["Top category", "Second category", "Other eligible purchases"], recalculatedMonthly: true, eligibleCategoriesOnly: true }, requiredTerms: ["3% cash back", "2% on the next", "1% on the rest"] },
      { fieldKey: "eligible_categories", displayValue: "Eight tracked categories: transportation, travel, grocery, entertainment, dining/nightlife, bills/utilities, health/beauty, and gas", valueJson: { categories: ["Transportation", "Travel", "Grocery", "Entertainment", "Dining & nightlife", "Bills & utilities", "Health & beauty", "Gas"] }, scopeJson: { merchantCodingApplies: true }, requiredTerms: ["Transportation", "Travel", "Grocery", "Dining & nightlife", "Bills & utilities", "Gas"] },
      { fieldKey: "annual_fee", displayValue: "No annual fee", valueJson: { annualFeeUsd: 0 }, scopeJson: { creditTermsApply: true }, requiredTerms: ["No annual fee"] },
      { fieldKey: "network_issuer", displayValue: "Visa credit card issued by Synchrony Bank", valueJson: { network: "Visa", issuer: "Synchrony Bank" }, scopeJson: { country: "US" }, requiredTerms: ["Visa", "issued by Synchrony Bank"] },
    ],
  },
  {
    candidateKey: "wayex-card",
    slug: "wayex-card-guide-2026",
    title: "Wayex Card Guide",
    url: "https://help.wayex.com/en/articles/9172848-wayex-card-guide",
    authorityTier: "B",
    sourceType: "official regional prepaid-card fee and limit guide",
    facts: [
      { fieldKey: "regional_scope", displayValue: "This evidence describes the Australian Wayex Visa prepaid product in AUD and must not be generalized globally", scopeJson: { country: "AU", currency: "AUD", product: "Visa prepaid" }, requiredTerms: ["AUD", "Visa"] },
      { fieldKey: "fees", displayValue: "A$14.99 card order; no renewal, ATM, deposit, or international FX fee; 1% crypto-to-AUD transaction fee", valueJson: { orderFeeAud: 14.99, renewalFeeAud: 0, atmIssuerFeeAud: 0, depositFeeAud: 0, internationalFxPercent: 0, cryptoToAudPercent: 1 }, scopeJson: { country: "AU", standardAtmChargesMayApply: true }, requiredTerms: ["14.99", "ATM Withdrawal Fee", "Crypto-to-AUD Transaction Fee", "1%", "International Foreign Exchange Fee"] },
      { fieldKey: "limits", displayValue: "A$10,000 per transaction; A$150,000 card lifetime; A$1,000 per ATM withdrawal and per day", valueJson: { transactionAud: 10000, lifetimeAud: 150000, atmSingleAud: 1000, atmDailyAud: 1000 }, scopeJson: { country: "AU" }, requiredTerms: ["AUD 10,000", "AUD 150,000", "AUD 1,000"] },
    ],
  },
];

export const remainingCatalogCandidateKeys = [...new Set(remainingCatalogSources.map(({ candidateKey }) => candidateKey))];
